name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v0.5.0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY_JSON_DEVELOP }}

    - name: Configure Docker to use gcloud as a credential helper
      run: |
        gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID_DEVELOP }}/frontenddevelop .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID_DEVELOP }}/frontenddevelop

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy frontenddevelop --image gcr.io/${{ secrets.GCP_PROJECT_ID_DEVELOP }}/frontenddevelop --region us-central1 --platform managed --allow-unauthenticated